var pokemon = {
    image : {},
    height : {},
    weight : {}
};

pokemon.image = {
    "Bulbasaur" : "image/001.jpg",
    "Ivysaur" : "image/002.jpg",
    "Venusaur" : "image/003.jpg",
    "Charmander" : "image/004.jpg",
    "Charmeleon" : "image/005.jpg",
    "Charizard" : "image/006.jpg",
    "Squirtle" : "image/007.jpg",
    "Wartortle" : "image/008.jpg",
    "Blastoise" : "image/009.jpg",
    "Caterpie" : "image/010.jpg",
    "Metapod" : "image/011.jpg",
    "Butterfree" : "image/012.jpg",
    "Weedle" : "image/013.jpg",
    "Kakuna" : "image/014.jpg",
    "Beedrill" : "image/015.jpg",
    "Pidgey" : "image/016.jpg",
    "Pidgeotto" : "image/017.jpg",
    "Pidgeot" : "image/018.jpg",
    "Rattata" : "image/019.jpg",
    "Raticate" : "image/020.jpg",
    "Spearow" : "image/021.jpg",
    "Fearow" : "image/022.jpg",
    "Ekans" : "image/023.jpg",
    "Arbok" : "image/024.jpg",
    "Pikachu" : "image/025.jpg",
    "Raichu" : "image/026.jpg",
    "Sandshrew" : "image/027.jpg",
    "Sandslash" : "image/028.jpg",
    "Nidoran F" : "image/029.jpg",
    "Nidorina" : "image/030.jpg",
    "Nidoqueen" : "image/031.jpg",
    "Nidoran M" : "image/032.jpg",
    "Nidorino" : "image/033.jpg",
    "Nidoking" : "image/034.jpg",
    "Clefairy" : "image/035.jpg",
    "Clefable" : "image/036.jpg",
    "Vulpix" : "image/037.jpg",
    "Ninetales" : "image/038.jpg",
    "Jigglypuff" : "image/039.jpg",
    "Wigglytuff" : "image/040.jpg",
    "Zubat" : "image/041.jpg",
    "Golbat" : "image/042.jpg",
    "Oddish" : "image/043.jpg",
    "Gloom" : "image/044.jpg",
    "Vileplume" : "image/045.jpg",
    "Paras" : "image/046.jpg",
    "Parasect" : "image/047.jpg",
    "Venonat" : "image/048.jpg",
    "Venomoth" : "image/049.jpg",
    "Diglett" : "image/050.jpg",
    "Dugtrio" : "image/051.jpg",
    "Meowth" : "image/052.jpg",
    "Persian" : "image/053.jpg",
    "Psyduck" : "image/054.jpg",
    "Golduck" : "image/055.jpg",
    "Mankey" : "image/056.jpg",
    "Primeape" : "image/057.jpg",
    "Growlithe" : "image/058.jpg",
    "Arcanine" : "image/059.jpg",
    "Poliwag" : "image/060.jpg",
    "Poliwhirl" : "image/061.jpg",
    "Poliwrath" : "image/062.jpg",
    "Abra" : "image/063.jpg",
    "Kadabra" : "image/064.jpg",
    "Alakazam" : "image/065.jpg",
    "Machop" : "image/066.jpg",
    "Machoke" : "image/067.jpg",
    "Machamp" : "image/068.jpg",
    "Bellsprout" : "image/069.jpg",
    "Weepinbell" : "image/070.jpg",
    "Victreebel" : "image/071.jpg",
    "Tentacool" : "image/072.jpg",
    "Tentacruel" : "image/073.jpg",
    "Geodude" : "image/074.jpg",
    "Graveler" : "image/075.jpg",
    "Golem" : "image/076.jpg",
    "Ponyta" : "image/077.jpg",
    "Rapidash" : "image/078.jpg",
    "Slowpoke" : "image/079.jpg",
    "Slowbro" : "image/080.jpg",
    "Magnemite" : "image/081.jpg",
    "Magneton" : "image/082.jpg",
    "Farfetch'd" : "image/083.jpg",
    "Doduo" : "image/084.jpg",
    "Dodrio" : "image/085.jpg",
    "Seel" : "image/086.jpg",
    "Dewgong" : "image/087.jpg",
    "Grimer" : "image/088.jpg",
    "Muk" : "image/089.jpg",
    "Shellder" : "image/090.jpg",
    "Cloyster" : "image/091.jpg",
    "Gastly" : "image/092.jpg",
    "Haunter" : "image/093.jpg",
    "Gengar" : "image/094.jpg",
    "Onix" : "image/095.jpg",
    "Drowzee" : "image/096.jpg",
    "Hypno" : "image/097.jpg",
    "Krabby" : "image/098.jpg",
    "Kingler" : "image/099.jpg",
    "Voltorb" : "image/100.jpg",
    "Electrode" : "image/101.jpg",
    "Exeggcute" : "image/102.jpg",
    "Exeggutor" : "image/103.jpg",
    "Cubone" : "image/104.jpg",
    "Marowak" : "image/105.jpg",
    "Hitmonlee" : "image/106.jpg",
    "Hitmonchan" : "image/107.jpg",
    "Lickitung" : "image/108.jpg",
    "Koffing" : "image/109.jpg",
    "Weezing" : "image/110.jpg",
    "Rhyhorn" : "image/111.jpg",
    "Rhydon" : "image/112.jpg",
    "Chansey" : "image/113.jpg",
    "Tangela" : "image/114.jpg",
    "Kangaskhan" : "image/115.jpg",
    "Horsea" : "image/116.jpg",
    "Seadra" : "image/117.jpg",
    "Goldeen" : "image/118.jpg",
    "Seaking" : "image/119.jpg",
    "Staryu" : "image/120.jpg",
    "Starmie" : "image/121.jpg",
    "Mr. Mime" : "image/122.jpg",
    "Scyther" : "image/123.jpg",
    "Jynx" : "image/124.jpg",
    "Electabuzz" : "image/125.jpg",
    "Magmar" : "image/126.jpg",
    "Pinsir" : "image/127.jpg",
    "Tauros" : "image/128.jpg",
    "Magikarp" : "image/129.jpg",
    "Gyarados" : "image/130.jpg",
    "Lapras" : "image/131.jpg",
    "Ditto" : "image/132.jpg",
    "Eevee" : "image/133.jpg",
    "Vaporeon" : "image/134.jpg",
    "Jolteon" : "image/135.jpg",
    "Flareon" : "image/136.jpg",
    "Porygon" : "image/137.jpg",
    "Omanyte" : "image/138.jpg",
    "Omastar" : "image/139.jpg",
    "Kabuto" : "image/140.jpg",
    "Kabutops" : "image/141.jpg",
    "Aerodactyl" : "image/142.jpg",
    "Snorlax" : "image/143.jpg",
    "Articuno" : "image/144.jpg",
    "Zapdos" : "image/145.jpg",
    "Moltres" : "image/146.jpg",
    "Dratini" : "image/147.jpg",
    "Dragonair" : "image/148.jpg",
    "Dragonite" : "image/149.jpg",
    "Mewtwo" : "image/150.jpg",
    "Mew" : "image/151.jpg"
};

pokemon.height = {
    "Bulbasaur" : "2 ft. 4 in.",
    "Ivysaur" : "3 ft. 3 in.",
    "Venusaur" : "7 ft. 7 in.",
    "Charmander" : "2 ft. 0 in.",
    "Charmeleon" : "4 ft. 7 in.",
    "Charizard" : "6 ft. 7 in.",
    "Squirtle" : "2 ft. 8 in.",
    "Wartortle" : "3 ft. 3 in.",
    "Blastoise" : "5 ft. 3 in.",
    "Caterpie" : "1 ft. 0 in.",
    "Metapod" : "2 ft. 4 in.",
    "Butterfree" : "4 ft. 7 in.",
    "Weedle" : "1 ft. 0 in.",
    "Kakuna" : "2 ft. 0 in.",
    "Beedrill" : "3 ft. 3 in.",
    "Pidgey" : "1 ft. 0 in.",
    "Pidgeotto" : "4 ft. 7 in.",
    "Pidgeot" : "5 ft. 11 in.",
    "Rattata" : "1 ft. 0 in.",
    "Raticate" : "2 ft. 4 in.",
    "Spearow" : "1 ft. 0 in.",
    "Fearow" : "4 ft. 11 in.",
    "Ekans" : "7 ft. 7 in.",
    "Arbok" : "11 ft. 6 in.",
    "Pikachu" : "1 ft. 4 in.",
    "Raichu" : "3 ft. 7 in.",
    "Sandshrew" : "2 ft. 0 in.",
    "Sandslash" : "3 ft. 3 in.",
    "Nidoran F" : "1 ft. 4 in.",
    "Nidorina" : "3 ft. 7 in.",
    "Nidoqueen" : "4 ft. 3 in.",
    "Nidoran M" : "1 ft. 4 in.",
    "Nidorino" : "3 ft. 11 in.",
    "Nidoking" : "5 ft. 7 in.",
    "Clefairy" : "2 ft. 0 in.",
    "Clefable" : "4 ft. 3 in.",
    "Vulpix" : "2 ft. 0 in.",
    "Ninetales" : "4 ft. 7 in.",
    "Jigglypuff" : "2 ft. 8 in.",
    "Wigglytuff" : "3 ft. 3 in.",
    "Zubat" : "3 ft. 7 in.",
    "Golbat" : "5 ft. 3 in.",
    "Oddish" : "2 ft. 8 in.",
    "Gloom" : "3 ft. 7 in.",
    "Vileplume" : "4 ft. 11 in.",
    "Paras" : "1 ft. 0 in.",
    "Parasect" : "3 ft. 3 in.",
    "Venonat" : "3 ft. 3 in.",
    "Venomoth" : "5 ft. 11 in.",
    "Diglett" : "1 ft. 8 in.",
    "Dugtrio" : "2 ft. 4 in.",
    "Meowth" : "1 ft. 4 in.",
    "Persian" : "3 ft. 3 in.",
    "Psyduck" : "3 ft. 7 in.",
    "Golduck" : "6 ft. 7 in.",
    "Mankey" : "2 ft. 8 in.",
    "Primeape" : "3 ft. 3 in.",
    "Growlithe" : "2 ft. 4 in.",
    "Arcanine" : "6 ft. 3 in.",
    "Poliwag" : "2 ft. 0 in.",
    "Poliwhirl" : "3 ft. 3 in.",
    "Poliwrath" : "4 ft. 3 in.",
    "Abra" : "3 ft. 11 in.",
    "Kadabra" : "4 ft. 3 in.",
    "Alakazam" : "5 ft. 11 in.",
    "Machop" : "3 ft. 7 in.",
    "Machoke" : "5 ft. 11 in.",
    "Machamp" : "5 ft. 3 in.",
    "Bellsprout" : "2 ft. 4 in.",
    "Weepinbell" : "3 ft. 3 in.",
    "Victreebel" : "6 ft. 7 in.",
    "Tentacool" : "3 ft. 11 in.",
    "Tentacruel" : "5 ft. 3 in.",
    "Geodude" : "1 ft. 4 in.",
    "Graveler" : "3 ft. 3 in.",
    "Golem" : "5 ft. 7 in.",
    "Ponyta" : "3 ft. 3 in.",
    "Rapidash" : "6 ft. 7 in.",
    "Slowpoke" : "4 ft. 11 in.",
    "Slowbro" : "5 ft. 3 in.",
    "Magnemite" : "1 ft. 0 in.",
    "Magneton" : "3 ft. 3 in.",
    "Farfetch'd" : "3 ft. 7 in.",
    "Doduo" : "5 ft. 7 in.",
    "Dodrio" : "6 ft. 11 in.",
    "Seel" : "4 ft. 7 in.",
    "Dewgong" : "6 ft. 7 in.",
    "Grimer" : "3 ft. 11 in.",
    "Muk" : "4 ft. 11 in.",
    "Shellder" : "1 ft. 0 in.",
    "Cloyster" : "5 ft. 11 in.",
    "Gastly" : "4 ft. 3 in.",
    "Haunter" : "5 ft. 3 in.",
    "Gengar" : "5 ft. 11 in.",
    "Onix" : "29 ft. 10 in.",
    "Drowzee" : "3 ft. 3 in.",
    "Hypno" : "5 ft. 3 in.",
    "Krabby" : "1 ft. 4 in.",
    "Kingler" : "4 ft. 3 in.",
    "Voltorb" : "2 ft. 8 in.",
    "Electrode" : "4 ft. 11 in.",
    "Exeggcute" : "1 ft. 4 in.",
    "Exeggutor" : "7 ft. 7 in.",
    "Cubone" : "1 ft. 4 in.",
    "Marowak" : "3 ft. 3 in.",
    "Hitmonlee" : "5 ft. 11 in.",
    "Hitmonchan" : "5 ft. 7 in.",
    "Lickitung" : "4 ft. 11 in.",
    "Koffing" : "2 ft. 0 in.",
    "Weezing" : "4 ft. 11 in.",
    "Rhyhorn" : "3 ft. 3 in.",
    "Rhydon" : "6 ft. 3 in.",
    "Chansey" : "4 ft. 7 in.",
    "Tangela" : "3 ft. 3 in.",
    "Kangaskhan" : "7 ft. 3 in.",
    "Horsea" : "1 ft. 4 in.",
    "Seadra" : "4 ft. 11 in.",
    "Goldeen" : "2 ft. 0 in.",
    "Seaking" : "4 ft. 3 in.",
    "Staryu" : "3 ft. 7 in.",
    "Starmie" : "4 ft. 7 in.",
    "Mr. Mime" : "4 ft. 11 in.",
    "Scyther" : "5 ft. 11 in.",
    "Jynx" : "5 ft. 7 in.",
    "Electabuzz" : "4 ft. 7 in.",
    "Magmar" : "4 ft. 3 in.",
    "Pinsir" : "5 ft. 11 in.",
    "Tauros" : "5 ft. 7 in.",
    "Magikarp" : "3 ft. 11 in.",
    "Gyarados" : "21 ft. 4 in.",
    "Lapras" : "8 ft. 2 in.",
    "Ditto" : "1 ft. 0 in.",
    "Eevee" : "1 ft. 0 in.",
    "Vaporeon" : "3 ft. 3 in.",
    "Jolteon" : "3 ft. 7 in.",
    "Flareon" : "3 ft. 11 in.",
    "Porygon" : "3 ft. 7 in.",
    "Omanyte" : "1 ft. 4 in.",
    "Omastar" : "3 ft. 3 in.",
    "Kabuto" : "2 ft. 8 in.",
    "Kabutops" : "4 ft. 3 in.",
    "Aerodactyl" : "6 ft. 11 in.",
    "Snorlax" : "7 ft. 11 in.",
    "Articuno" : "6 ft. 7 in.",
    "Zapdos" : "5 ft. 3 in.",
    "Moltres" : "7 ft. 7 in.",
    "Dratini" : "6 ft. 11 in.",
    "Dragonair" : "13 ft. 1 in.",
    "Dragonite" : "7 ft. 3 in.",
    "Mewtwo" : "7 ft. 7 in.",
    "Mew" : "1 ft. 4 in."
};

pokemon.weight = {
    "Bulbasaur" : "15.2 lb.",
    "Ivysaur" : "28.7 lb.",
    "Venusaur" : "220.5 lb.",
    "Charmander" : "18.7 lb.",
    "Charmeleon" : "41.9 lb.",
    "Charizard" : "199.6 lb.",
    "Squirtle" : "19.8 lb.",
    "Wartortle" : "49.6 lb.",
    "Blastoise" : "188.5 lb.",
    "Caterpie" : "6.4 lb.",
    "Metapod" : "21.8 lb.",
    "Butterfree" : "70.6 lb.",
    "Weedle" : "7.1 lb.",
    "Kakuna" : "22.1 lb.",
    "Beedrill" : "65.0 lb.",
    "Pidgey" : "4.0 lb.",
    "Pidgeotto" : "66.2 lb.",
    "Pidgeot" : "87.1 lb.",
    "Rattata" : "7.7 lb.",
    "Raticate" : "40.8 lb.",
    "Spearow" : "4.4 lb.",
    "Fearow" : "83.8 lb.",
    "Ekans" : "15.2 lb.",
    "Arbok" : "143.3 lb.",
    "Pikachu" : "13.2 lb.",
    "Raichu" : "66.2 lb.",
    "Sandshrew" : "26.5 lb.",
    "Sandslash" : "65.0 lb.",
    "Nidoran F" : "15.4 lb.",
    "Nidorina" : "44.1 lb.",
    "Nidoqueen" : "132.3 lb.",
    "Nidoran M" : "15.4 lb.",
    "Nidorino" : "43.0 lb.",
    "Nidoking" : "136.7 lb.",
    "Clefairy" : "16.5 lb.",
    "Clefable" : "88.2 lb.",
    "Vulpix" : "21.8 lb.",
    "Ninetales" : "43.9 lb.",
    "Jigglypuff" : "12.1 lb.",
    "Wigglytuff" : "26.5 lb.",
    "Zubat" : "16.5 lb.",
    "Golbat" : "121.3 lb.",
    "Oddish" : "11.9 lb.",
    "Gloom" : "19.0 lb.",
    "Vileplume" : "41.0 lb.",
    "Paras" : "11.9 lb.",
    "Parasect" : "65.0 lb.",
    "Venonat" : "66.2 lb.",
    "Venomoth" : "27.6 lb.",
    "Diglett" : "1.8 lb.",
    "Dugtrio" : "73.4 lb.",
    "Meowth" : "9.3 lb.",
    "Persian" : "70.6 lb.",
    "Psyduck" : "43.2 lb.",
    "Golduck" : "168.9 lb.",
    "Mankey" : "61.7 lb.",
    "Primeape" : "70.6 lb.",
    "Growlithe" : "41.9 lb.",
    "Arcanine" : "341.8 lb.",
    "Poliwag" : "27.3 lb.",
    "Poliwhirl" : "44.1 lb.",
    "Poliwrath" : "119.1 lb.",
    "Abra" : "43.0 lb.",
    "Kadabra" : "124.6 lb.",
    "Alakazam" : "105.8 lb.",
    "Machop" : "43.0 lb.",
    "Machoke" : "155.5 lb.",
    "Machamp" : "286.6 lb.",
    "Bellsprout" : "8.8 lb.",
    "Weepinbell" : "14.1 lb.",
    "Victreebel" : "34.2 lb.",
    "Tentacool" : "100.3 lb.",
    "Tentacruel" : "121.3 lb.",
    "Geodude" : "44.1 lb.",
    "Graveler" : "231.5 lb.",
    "Golem" : "661.5 lb.",
    "Ponyta" : "66.2 lb.",
    "Rapidash" : "209.5 lb.",
    "Slowpoke" : "79.4 lb.",
    "Slowbro" : "173.1 lb.",
    "Magnemite" : "13.2 lb.",
    "Magneton" : "132.3 lb.",
    "Farfetch'd" : "33.1 lb.",
    "Doduo" : "86.4 lb.",
    "Dodrio" : "187.9 lb.",
    "Seel" : "198.4 lb.",
    "Dewgong" : "264.6 lb.",
    "Grimer" : "66.2 lb.",
    "Muk" : "66.2 lb.",
    "Shellder" : "8.8 lb.",
    "Cloyster" : "292.2 lb.",
    "Gastly" : "0.2 lb.",
    "Haunter" : "0.2 lb.",
    "Gengar" : "89.3 lb.",
    "Onix" : "463.1 lb.",
    "Drowzee" : "71.4 lb.",
    "Hypno" : "166.7 lb.",
    "Krabby" : "14.3 lb.",
    "Kingler" : "132.3 lb.",
    "Voltorb" : "22.9 lb.",
    "Electrode" : "146.9 lb.",
    "Exeggcute" : "5.5 lb.",
    "Exeggutor" : "264.6 lb.",
    "Cubone" : "14.3 lb.",
    "Marowak" : "99.2 lb.",
    "Hitmonlee" : "109.8 lb.",
    "Hitmonchan" : "110.7 lb.",
    "Lickitung" : "144.4 lb.",
    "Koffing" : "2.2 lb.",
    "Weezing" : "20.9 lb.",
    "Rhyhorn" : "253.6 lb.",
    "Rhydon" : "264.6 lb.",
    "Chansey" : "76.3 lb.",
    "Tangela" : "77.2 lb.",
    "Kangaskhan" : "176.4 lb.",
    "Horsea" : "17.6 lb.",
    "Seadra" : "55.1 lb.",
    "Goldeen" : "33.1 lb.",
    "Seaking" : "86.0 lb.",
    "Staryu" : "76.1 lb.",
    "Starmie" : "176.4 lb.",
    "Mr. Mime" : "66.2 lb.",
    "Scyther" : "123.5 lb.",
    "Jynx" : "89.5 lb.",
    "Electabuzz" : "66.2 lb.",
    "Magmar" : "98.1 lb.",
    "Pinsir" : "121.3 lb.",
    "Tauros" : "194.9 lb.",
    "Magikarp" : "22.1 lb.",
    "Gyarados" : "518.2 lb.",
    "Lapras" : "485.1 lb.",
    "Ditto" : "8.8 lb.",
    "Eevee" : "14.3 lb.",
    "Vaporeon" : "63.9 lb.",
    "Jolteon" : "54.0 lb.",
    "Flareon" : "55.1 lb.",
    "Porygon" : "80.5 lb.",
    "Omanyte" : "16.5 lb.",
    "Omastar" : "77.2 lb.",
    "Kabuto" : "25.4 lb.",
    "Kabutops" : "89.3 lb.",
    "Aerodactyl" : "130.1 lb.",
    "Snorlax" : "1014.3 lb.",
    "Articuno" : "122.2 lb.",
    "Zapdos" : "116.0 lb.",
    "Moltres" : "132.3 lb.",
    "Dratini" : "7.3 lb.",
    "Dragonair" : "36.4 lb.",
    "Dragonite" : "463.1 lb.",
    "Mewtwo" : "269.0 lb.",
    "Mew" : "8.8 lb."
};