var pokemon = {
  images: {},
  powers: {},
  names: [],
  weights: {},
  heights: {}
}

pokemon.images = {
  'Oddish': 'public/images/043.jpg',
  'Weezing': 'public/images/110.jpg',
  'Magikarp': 'public/images/129.jpg',
  'Jynx': 'public/images/124.jpg',
  'Paras': 'public/images/046.jpg',
  'Kadabra': 'public/images/064.jpg',
  'Sandslash': 'public/images/028.jpg',
  'Beedrill': 'public/images/015.jpg',
  'Hitmonlee': 'public/images/106.jpg',
  'Poliwrath': 'public/images/062.jpg',
  'Machamp': 'public/images/068.jpg',
  'Butterfree': 'public/images/012.jpg',
  'Raichu': 'public/images/026.jpg',
  'Omanyte': 'public/images/138.jpg',
  'Tangela': 'public/images/114.jpg',
  'Slowpoke': 'public/images/079.jpg',
  'Mew': 'public/images/151.jpg',
  'Diglett': 'public/images/050.jpg',
  'Rhydon': 'public/images/112.jpg',
  'Poliwhirl': 'public/images/061.jpg',
  'Farfetch\'d': 'public/images/083.jpg',
  'Raticate': 'public/images/020.jpg',
  'Tentacool': 'public/images/072.jpg',
  'Magnemite': 'public/images/081.jpg',
  'Ditto': 'public/images/132.jpg',
  'Aerodactyl': 'public/images/142.jpg',
  'Koffing': 'public/images/109.jpg',
  'Shellder': 'public/images/090.jpg',
  'Magmar': 'public/images/126.jpg',
  'Mankey': 'public/images/056.jpg',
  'Dratini': 'public/images/147.jpg',
  'Nidoqueen': 'public/images/031.jpg',
  'Charmeleon': 'public/images/005.jpg',
  'Psyduck': 'public/images/054.jpg',
  'Slowbro': 'public/images/080.jpg',
  'Snorlax': 'public/images/143.jpg',
  'Arcanine': 'public/images/059.jpg',
  'Omastar': 'public/images/139.jpg',
  'Growlithe': 'public/images/058.jpg',
  'Articuno': 'public/images/144.jpg',
  'Blastoise': 'public/images/009.jpg',
  'Golem': 'public/images/076.jpg',
  'Krabby': 'public/images/098.jpg',
  'Pinsir': 'public/images/127.jpg',
  'Cloyster': 'public/images/091.jpg',
  'Kangaskhan': 'public/images/115.jpg',
  'Tauros': 'public/images/128.jpg',
  'Fearow': 'public/images/022.jpg',
  'Bulbasaur': 'public/images/001.jpg',
  'Jigglypuff': 'public/images/039.jpg',
  'Abra': 'public/images/063.jpg',
  'Arbok': 'public/images/024.jpg',
  'Doduo': 'public/images/084.jpg',
  'Muk': 'public/images/089.jpg',
  'Marowak': 'public/images/105.jpg',
  'Wartortle': 'public/images/008.jpg',
  'Wigglytuff': 'public/images/040.jpg',
  'Porygon': 'public/images/137.jpg',
  'Graveler': 'public/images/075.jpg',
  'Chansey': 'public/images/113.jpg',
  'Geodude': 'public/images/074.jpg',
  'Pidgeotto': 'public/images/017.jpg',
  'Rattata': 'public/images/019.jpg',
  'Mewtwo': 'public/images/150.jpg',
  'Primeape': 'public/images/057.jpg',
  'Squirtle': 'public/images/007.jpg',
  'Vulpix': 'public/images/037.jpg',
  'Zapdos': 'public/images/145.jpg',
  'Bellsprout': 'public/images/069.jpg',
  'Jolteon': 'public/images/135.jpg',
  'Venusaur': 'public/images/003.jpg',
  'Poliwag': 'public/images/060.jpg',
  'Spearow': 'public/images/021.jpg',
  'Golduck': 'public/images/055.jpg',
  'Ekans': 'public/images/023.jpg',
  'Alakazam': 'public/images/065.jpg',
  'Kabutops': 'public/images/141.jpg',
  'Seel': 'public/images/086.jpg',
  'Voltorb': 'public/images/100.jpg',
  'Dragonite': 'public/images/149.jpg',
  'Gyarados': 'public/images/130.jpg',
  'Vaporeon': 'public/images/134.jpg',
  'Metapod': 'public/images/011.jpg',
  'Dragonair': 'public/images/148.jpg',
  'Ponyta': 'public/images/077.jpg',
  'Lickitung': 'public/images/108.jpg',
  'Haunter': 'public/images/093.jpg',
  'Ivysaur': 'public/images/002.jpg',
  'Onix': 'public/images/095.jpg',
  'Gastly': 'public/images/092.jpg',
  'Drowzee': 'public/images/096.jpg',
  'Goldeen': 'public/images/118.jpg',
  'Pidgey': 'public/images/016.jpg',
  'Hypno': 'public/images/097.jpg',
  'Machoke': 'public/images/067.jpg',
  'Exeggutor': 'public/images/103.jpg',
  'Meowth': 'public/images/052.jpg',
  'Eevee': 'public/images/133.jpg',
  'Sandshrew': 'public/images/027.jpg',
  'Venomoth': 'public/images/049.jpg',
  'Victreebel': 'public/images/071.jpg',
  'Nidorino': 'public/images/033.jpg',
  'Nidorina': 'public/images/030.jpg',
  'Pidgeot': 'public/images/018.jpg',
  'Tentacruel': 'public/images/073.jpg',
  'Kingler': 'public/images/099.jpg',
  'Exeggcute': 'public/images/102.jpg',
  'Weepinbell': 'public/images/070.jpg',
  'Golbat': 'public/images/042.jpg',
  'Gengar': 'public/images/094.jpg',
  'Rapidash': 'public/images/078.jpg',
  'Parasect': 'public/images/047.jpg',
  'Dugtrio': 'public/images/051.jpg',
  'Dodrio': 'public/images/085.jpg',
  'Seadra': 'public/images/117.jpg',
  'Persian': 'public/images/053.jpg',
  'Nidoking': 'public/images/034.jpg',
  'Scyther': 'public/images/123.jpg',
  'Zubat': 'public/images/041.jpg',
  'Charmander': 'public/images/004.jpg',
  'Electrode': 'public/images/101.jpg',
  'Moltres': 'public/images/146.jpg',
  'Gloom': 'public/images/044.jpg',
  'Flareon': 'public/images/136.jpg',
  'Kabuto': 'public/images/140.jpg',
  'Electabuzz': 'public/images/125.jpg',
  'Venonat': 'public/images/048.jpg',
  'Charizard': 'public/images/006.jpg',
  'Pikachu': 'public/images/025.jpg',
  'Machop': 'public/images/066.jpg',
  'Caterpie': 'public/images/010.jpg',
  'Kakuna': 'public/images/014.jpg',
  'Horsea': 'public/images/116.jpg',
  'Seaking': 'public/images/119.jpg',
  'Dewgong': 'public/images/087.jpg',
  'Hitmonchan': 'public/images/107.jpg',
  'Clefable': 'public/images/036.jpg',
  'Nidoran F': 'public/images/029.jpg',
  'Starmie': 'public/images/121.jpg',
  'Rhyhorn': 'public/images/111.jpg',
  'Nidoran M': 'public/images/032.jpg',
  'Ninetales': 'public/images/038.jpg',
  'Cubone': 'public/images/104.jpg',
  'Weedle': 'public/images/013.jpg',
  'Vileplume': 'public/images/045.jpg',
  'Clefairy': 'public/images/035.jpg',
  'Grimer': 'public/images/088.jpg',
  'Magneton': 'public/images/082.jpg',
  'Mr. Mime': 'public/images/122.jpg',
  'Lapras': 'public/images/131.jpg',
  'Staryu': 'public/images/120.jpg'
}

pokemon.powers = {
  'Oddish': '320',
  'Weezing': '490',
  'Magikarp': '200',
  'Jynx': '455',
  'Paras': '285',
  'Kadabra': '400',
  'Sandslash': '450',
  'Beedrill': '395',
  'Hitmonlee': '455',
  'Poliwrath': '510',
  'Machamp': '505',
  'Butterfree': '395',
  'Raichu': '485',
  'Omanyte': '355',
  'Tangela': '435',
  'Slowpoke': '315',
  'Mew': '600',
  'Diglett': '265',
  'Rhydon': '485',
  'Poliwhirl': '385',
  'Farfetch\'d': '352',
  'Raticate': '413',
  'Tentacool': '335',
  'Magnemite': '325',
  'Ditto': '288',
  'Aerodactyl': '515',
  'Koffing': '340',
  'Shellder': '305',
  'Magmar': '495',
  'Mankey': '305',
  'Dratini': '300',
  'Nidoqueen': '505',
  'Charmeleon': '405',
  'Psyduck': '320',
  'Slowbro': '490',
  'Snorlax': '540',
  'Arcanine': '555',
  'Omastar': '495',
  'Growlithe': '350',
  'Articuno': '580',
  'Blastoise': '530',
  'Golem': '495',
  'Krabby': '325',
  'Pinsir': '500',
  'Cloyster': '525',
  'Kangaskhan': '490',
  'Tauros': '490',
  'Fearow': '442',
  'Bulbasaur': '318',
  'Jigglypuff': '270',
  'Abra': '310',
  'Arbok': '438',
  'Doduo': '310',
  'Muk': '500',
  'Marowak': '425',
  'Wartortle': '405',
  'Wigglytuff': '435',
  'Porygon': '395',
  'Graveler': '390',
  'Chansey': '450',
  'Geodude': '300',
  'Pidgeotto': '349',
  'Rattata': '253',
  'Mewtwo': '680',
  'Primeape': '455',
  'Squirtle': '314',
  'Vulpix': '299',
  'Zapdos': '580',
  'Bellsprout': '300',
  'Jolteon': '525',
  'Venusaur': '525',
  'Poliwag': '300',
  'Spearow': '262',
  'Golduck': '500',
  'Ekans': '288',
  'Alakazam': '500',
  'Kabutops': '495',
  'Seel': '325',
  'Voltorb': '330',
  'Dragonite': '600',
  'Gyarados': '540',
  'Vaporeon': '525',
  'Metapod': '205',
  'Dragonair': '420',
  'Ponyta': '410',
  'Lickitung': '385',
  'Haunter': '405',
  'Ivysaur': '405',
  'Onix': '385',
  'Gastly': '310',
  'Drowzee': '328',
  'Goldeen': '320',
  'Pidgey': '251',
  'Hypno': '483',
  'Machoke': '405',
  'Exeggutor': '520',
  'Meowth': '290',
  'Eevee': '325',
  'Sandshrew': '300',
  'Venomoth': '450',
  'Victreebel': '490',
  'Nidorino': '365',
  'Nidorina': '365',
  'Pidgeot': '479',
  'Tentacruel': '515',
  'Kingler': '475',
  'Exeggcute': '325',
  'Weepinbell': '390',
  'Golbat': '455',
  'Gengar': '500',
  'Rapidash': '500',
  'Parasect': '405',
  'Dugtrio': '405',
  'Dodrio': '460',
  'Seadra': '440',
  'Persian': '440',
  'Nidoking': '505',
  'Scyther': '500',
  'Zubat': '245',
  'Charmander': '309',
  'Electrode': '480',
  'Moltres': '580',
  'Gloom': '395',
  'Flareon': '525',
  'Kabuto': '355',
  'Electabuzz': '490',
  'Venonat': '305',
  'Charizard': '534',
  'Pikachu': '320',
  'Machop': '305',
  'Caterpie': '195',
  'Kakuna': '205',
  'Horsea': '295',
  'Seaking': '450',
  'Dewgong': '475',
  'Hitmonchan': '455',
  'Clefable': '483',
  'Nidoran F': '275',
  'Starmie': '520',
  'Rhyhorn': '345',
  'Nidoran M': '273',
  'Ninetales': '505',
  'Cubone': '320',
  'Weedle': '195',
  'Vileplume': '490',
  'Clefairy': '323',
  'Grimer': '325',
  'Magneton': '465',
  'Mr. Mime': '460',
  'Lapras': '535',
  'Staryu': '340'
}

pokemon.names = [
  'Bulbasaur',
  'Ivysaur',
  'Venusaur',
  'Charmander',
  'Charmeleon',
  'Charizard',
  'Squirtle',
  'Wartortle',
  'Blastoise',
  'Caterpie',
  'Metapod',
  'Butterfree',
  'Weedle',
  'Kakuna',
  'Beedrill',
  'Pidgey',
  'Pidgeotto',
  'Pidgeot',
  'Rattata',
  'Raticate',
  'Spearow',
  'Fearow',
  'Ekans',
  'Arbok',
  'Pikachu',
  'Raichu',
  'Sandshrew',
  'Sandslash',
  'Nidoran F',
  'Nidorina',
  'Nidoqueen',
  'Nidoran M',
  'Nidorino',
  'Nidoking',
  'Clefairy',
  'Clefable',
  'Vulpix',
  'Ninetales',
  'Jigglypuff',
  'Wigglytuff',
  'Zubat',
  'Golbat',
  'Oddish',
  'Gloom',
  'Vileplume',
  'Paras',
  'Parasect',
  'Venonat',
  'Venomoth',
  'Diglett',
  'Dugtrio',
  'Meowth',
  'Persian',
  'Psyduck',
  'Golduck',
  'Mankey',
  'Primeape',
  'Growlithe',
  'Arcanine',
  'Poliwag',
  'Poliwhirl',
  'Poliwrath',
  'Abra',
  'Kadabra',
  'Alakazam',
  'Machop',
  'Machoke',
  'Machamp',
  'Bellsprout',
  'Weepinbell',
  'Victreebel',
  'Tentacool',
  'Tentacruel',
  'Geodude',
  'Graveler',
  'Golem',
  'Ponyta',
  'Rapidash',
  'Slowpoke',
  'Slowbro',
  'Magnemite',
  'Magneton',
  'Farfetch\'d',
  'Doduo',
  'Dodrio',
  'Seel',
  'Dewgong',
  'Grimer',
  'Muk',
  'Shellder',
  'Cloyster',
  'Gastly',
  'Haunter',
  'Gengar',
  'Onix',
  'Drowzee',
  'Hypno',
  'Krabby',
  'Kingler',
  'Voltorb',
  'Electrode',
  'Exeggcute',
  'Exeggutor',
  'Cubone',
  'Marowak',
  'Hitmonlee',
  'Hitmonchan',
  'Lickitung',
  'Koffing',
  'Weezing',
  'Rhyhorn',
  'Rhydon',
  'Chansey',
  'Tangela',
  'Kangaskhan',
  'Horsea',
  'Seadra',
  'Goldeen',
  'Seaking',
  'Staryu',
  'Starmie',
  'Mr. Mime',
  'Scyther',
  'Jynx',
  'Electabuzz',
  'Magmar',
  'Pinsir',
  'Tauros',
  'Magikarp',
  'Gyarados',
  'Lapras',
  'Ditto',
  'Eevee',
  'Vaporeon',
  'Jolteon',
  'Flareon',
  'Porygon',
  'Omanyte',
  'Omastar',
  'Kabuto',
  'Kabutops',
  'Aerodactyl',
  'Snorlax',
  'Articuno',
  'Zapdos',
  'Moltres',
  'Dratini',
  'Dragonair',
  'Dragonite',
  'Mewtwo',
  'Mew'
]

pokemon.weights = {
  'Oddish': '11.9 lbs.',
  'Weezing': '20.9 lbs.',
  'Magikarp': '22 lbs.',
  'Jynx': '89.5 lbs.',
  'Paras': '11.9 lbs.',
  'Kadabra': '124.6 lbs.',
  'Sandslash': '65 lbs.',
  'Beedrill': '65 lbs.',
  'Hitmonlee': '109.8 lbs.',
  'Poliwrath': '119 lbs.',
  'Machamp': '286.6 lbs.',
  'Butterfree': '70.5 lbs.',
  'Raichu': '66.1 lbs.',
  'Omanyte': '16.5 lbs.',
  'Tangela': '77.2 lbs.',
  'Slowpoke': '79.4 lbs.',
  'Mew': '8.8 lbs.',
  'Diglett': '1.8 lbs.',
  'Rhydon': '264.6 lbs.',
  'Poliwhirl': '44.1 lbs.',
  'Farfetch\'d': '33.1 lbs.',
  'Raticate': '40.8 lbs.',
  'Tentacool': '100.3 lbs.',
  'Magnemite': '13.2 lbs.',
  'Ditto': '8.8 lbs.',
  'Aerodactyl': '130.1 lbs.',
  'Koffing': '2.2 lbs.',
  'Shellder': '8.8 lbs.',
  'Magmar': '98.1 lbs.',
  'Mankey': '61.7 lbs.',
  'Dratini': '7.3 lbs.',
  'Nidoqueen': '132.3 lbs.',
  'Charmeleon': '41.9 lbs.',
  'Psyduck': '43.2 lbs.',
  'Slowbro': '173.1 lbs.',
  'Snorlax': '1014.1 lbs.',
  'Arcanine': '341.7 lbs.',
  'Omastar': '77.2 lbs.',
  'Growlithe': '41.9 lbs.',
  'Articuno': '122.1 lbs.',
  'Blastoise': '188.5 lbs.',
  'Golem': '661.4 lbs.',
  'Krabby': '14.3 lbs.',
  'Pinsir': '121.3 lbs.',
  'Cloyster': '292.1 lbs.',
  'Kangaskhan': '176.4 lbs.',
  'Tauros': '194.9 lbs.',
  'Fearow': '83.8 lbs.',
  'Bulbasaur': '15.2 lbs.',
  'Jigglypuff': '12.1 lbs.',
  'Abra': '43 lbs.',
  'Arbok': '143.3 lbs.',
  'Doduo': '86.4 lbs.',
  'Muk': '66.1 lbs.',
  'Marowak': '99.2 lbs.',
  'Wartortle': '49.6 lbs.',
  'Wigglytuff': '26.5 lbs.',
  'Porygon': '80.5 lbs.',
  'Graveler': '231.5 lbs.',
  'Chansey': '76.3 lbs.',
  'Geodude': '44.1 lbs.',
  'Pidgeotto': '66.1 lbs.',
  'Rattata': '7.7 lbs.',
  'Mewtwo': '269 lbs.',
  'Primeape': '70.5 lbs.',
  'Squirtle': '19.8 lbs.',
  'Vulpix': '21.8 lbs.',
  'Zapdos': '116 lbs.',
  'Bellsprout': '8.8 lbs.',
  'Jolteon': '54 lbs.',
  'Venusaur': '220.5 lbs.',
  'Poliwag': '27.3 lbs.',
  'Spearow': '4.4 lbs.',
  'Golduck': '168.9 lbs.',
  'Ekans': '15.2 lbs.',
  'Alakazam': '105.8 lbs.',
  'Kabutops': '89.3 lbs.',
  'Seel': '198.4 lbs.',
  'Voltorb': '22.9 lbs.',
  'Dragonite': '463 lbs.',
  'Gyarados': '518.1 lbs.',
  'Vaporeon': '63.9 lbs.',
  'Metapod': '21.8 lbs.',
  'Dragonair': '36.4 lbs.',
  'Ponyta': '66.1 lbs.',
  'Lickitung': '144.4 lbs.',
  'Haunter': '0.2 lbs.',
  'Ivysaur': '28.7 lbs.',
  'Onix': '463 lbs.',
  'Gastly': '0.2 lbs.',
  'Drowzee': '71.4 lbs.',
  'Goldeen': '33.1 lbs.',
  'Pidgey': '4 lbs.',
  'Hypno': '166.7 lbs.',
  'Machoke': '155.4 lbs.',
  'Exeggutor': '264.6 lbs.',
  'Meowth': '9.3 lbs.',
  'Eevee': '14.3 lbs.',
  'Sandshrew': '26.5 lbs.',
  'Venomoth': '27.6 lbs.',
  'Victreebel': '34.2 lbs.',
  'Nidorino': '43 lbs.',
  'Nidorina': '44.1 lbs.',
  'Pidgeot': '87.1 lbs.',
  'Tentacruel': '121.3 lbs.',
  'Kingler': '132.3 lbs.',
  'Exeggcute': '5.5 lbs.',
  'Weepinbell': '14.1 lbs.',
  'Golbat': '121.3 lbs.',
  'Gengar': '89.3 lbs.',
  'Rapidash': '209.4 lbs.',
  'Parasect': '65 lbs.',
  'Dugtrio': '73.4 lbs.',
  'Dodrio': '187.8 lbs.',
  'Seadra': '55.1 lbs.',
  'Persian': '70.5 lbs.',
  'Nidoking': '136.7 lbs.',
  'Scyther': '123.5 lbs.',
  'Zubat': '16.5 lbs.',
  'Charmander': '18.7 lbs.',
  'Electrode': '146.8 lbs.',
  'Moltres': '132.3 lbs.',
  'Gloom': '19 lbs.',
  'Flareon': '55.1 lbs.',
  'Kabuto': '25.4 lbs.',
  'Electabuzz': '66.1 lbs.',
  'Venonat': '66.1 lbs.',
  'Charizard': '199.5 lbs.',
  'Pikachu': '13.2 lbs.',
  'Machop': '43 lbs.',
  'Caterpie': '6.4 lbs.',
  'Kakuna': '22 lbs.',
  'Horsea': '17.6 lbs.',
  'Seaking': '86 lbs.',
  'Dewgong': '264.6 lbs.',
  'Hitmonchan': '110.7 lbs.',
  'Clefable': '88.2 lbs.',
  'Nidoran F': '15.4 lbs.',
  'Starmie': '176.4 lbs.',
  'Rhyhorn': '253.5 lbs.',
  'Nidoran M': '19.8 lbs.',
  'Ninetales': '43.9 lbs.',
  'Cubone': '14.3 lbs.',
  'Weedle': '7.1 lbs.',
  'Vileplume': '41 lbs.',
  'Clefairy': '16.5 lbs.',
  'Grimer': '66.1 lbs.',
  'Magneton': '132.3 lbs.',
  'Mr. Mime': '120.2 lbs.',
  'Lapras': '485 lbs.',
  'Staryu': '76.1 lbs.'
}

pokemon.heights = {
  'Oddish': '1 ft. 8 in.',
  'Weezing': '3 ft. 11 in.',
  'Magikarp': '2 ft. 11 in.',
  'Jynx': '4 ft. 7 in.',
  'Paras': '1 ft. 0 in.',
  'Kadabra': '4 ft. 3 in.',
  'Sandslash': '3 ft. 3 in.',
  'Beedrill': '3 ft. 3 in.',
  'Hitmonlee': '4 ft. 11 in.',
  'Poliwrath': '4 ft. 3 in.',
  'Machamp': '5 ft. 3 in.',
  'Butterfree': '3 ft. 7 in.',
  'Raichu': '2 ft. 7 in.',
  'Omanyte': '1 ft. 4 in.',
  'Tangela': '3 ft. 3 in.',
  'Slowpoke': '3 ft. 11 in.',
  'Mew': '1 ft. 4 in.',
  'Diglett': '0 ft. 8 in.',
  'Rhydon': '6 ft. 3 in.',
  'Poliwhirl': '3 ft. 3 in.',
  'Farfetch\'d': '2 ft. 7 in.',
  'Raticate': '2 ft. 4 in.',
  'Tentacool': '2 ft. 11 in.',
  'Magnemite': '1 ft. 0 in.',
  'Ditto': '1 ft. 0 in.',
  'Aerodactyl': '5 ft. 11 in.',
  'Koffing': '2 ft. 0 in.',
  'Shellder': '1 ft. 0 in.',
  'Magmar': '4 ft. 3 in.',
  'Mankey': '1 ft. 8 in.',
  'Dratini': '5 ft. 11 in.',
  'Nidoqueen': '4 ft. 3 in.',
  'Charmeleon': '3 ft. 7 in.',
  'Psyduck': '2 ft. 7 in.',
  'Slowbro': '5 ft. 3 in.',
  'Snorlax': '6 ft. 11 in.',
  'Arcanine': '6 ft. 3 in.',
  'Omastar': '3 ft. 3 in.',
  'Growlithe': '2 ft. 4 in.',
  'Articuno': '5 ft. 7 in.',
  'Blastoise': '5 ft. 3 in.',
  'Golem': '4 ft. 7 in.',
  'Krabby': '1 ft. 4 in.',
  'Pinsir': '4 ft. 11 in.',
  'Cloyster': '4 ft. 11 in.',
  'Kangaskhan': '7 ft. 3 in.',
  'Tauros': '4 ft. 7 in.',
  'Fearow': '3 ft. 11 in.',
  'Bulbasaur': '2 ft. 4 in.',
  'Jigglypuff': '1 ft. 8 in.',
  'Abra': '2 ft. 11 in.',
  'Arbok': '11 ft. 6 in.',
  'Doduo': '4 ft. 7 in.',
  'Muk': '3 ft. 11 in.',
  'Marowak': '3 ft. 3 in.',
  'Wartortle': '3 ft. 3 in.',
  'Wigglytuff': '3 ft. 3 in.',
  'Porygon': '2 ft. 7 in.',
  'Graveler': '3 ft. 3 in.',
  'Chansey': '3 ft. 7 in.',
  'Geodude': '1 ft. 4 in.',
  'Pidgeotto': '3 ft. 7 in.',
  'Rattata': '1 ft. 0 in.',
  'Mewtwo': '6 ft. 7 in.',
  'Primeape': '3 ft. 3 in.',
  'Squirtle': '1 ft. 8 in.',
  'Vulpix': '2 ft. 0 in.',
  'Zapdos': '5 ft. 3 in.',
  'Bellsprout': '2 ft. 4 in.',
  'Jolteon': '2 ft. 7 in.',
  'Venusaur': '6 ft. 7 in.',
  'Poliwag': '2 ft. 0 in.',
  'Spearow': '1 ft. 0 in.',
  'Golduck': '5 ft. 7 in.',
  'Ekans': '6 ft. 7 in.',
  'Alakazam': '4 ft. 11 in.',
  'Kabutops': '4 ft. 3 in.',
  'Seel': '3 ft. 7 in.',
  'Voltorb': '1 ft. 8 in.',
  'Dragonite': '7 ft. 3 in.',
  'Gyarados': '21 ft. 4 in.',
  'Vaporeon': '3 ft. 3 in.',
  'Metapod': '2 ft. 4 in.',
  'Dragonair': '13 ft. 1 in.',
  'Ponyta': '3 ft. 3 in.',
  'Lickitung': '3 ft. 11 in.',
  'Haunter': '5 ft. 3 in.',
  'Ivysaur': '3 ft. 3 in.',
  'Onix': '28 ft. 10 in.',
  'Gastly': '4 ft. 3 in.',
  'Drowzee': '3 ft. 3 in.',
  'Goldeen': '2 ft. 0 in.',
  'Pidgey': '1 ft. 0 in.',
  'Hypno': '5 ft. 3 in.',
  'Machoke': '4 ft. 11 in.',
  'Exeggutor': '6 ft. 7 in.',
  'Meowth': '1 ft. 4 in.',
  'Eevee': '1 ft. 0 in.',
  'Sandshrew': '2 ft. 0 in.',
  'Venomoth': '4 ft. 11 in.',
  'Victreebel': '5 ft. 7 in.',
  'Nidorino': '2 ft. 11 in.',
  'Nidorina': '2 ft. 7 in.',
  'Pidgeot': '4 ft. 11 in.',
  'Tentacruel': '5 ft. 3 in.',
  'Kingler': '4 ft. 3 in.',
  'Exeggcute': '1 ft. 4 in.',
  'Weepinbell': '3 ft. 3 in.',
  'Golbat': '5 ft. 3 in.',
  'Gengar': '4 ft. 11 in.',
  'Rapidash': '5 ft. 7 in.',
  'Parasect': '3 ft. 3 in.',
  'Dugtrio': '2 ft. 4 in.',
  'Dodrio': '5 ft. 11 in.',
  'Seadra': '3 ft. 11 in.',
  'Persian': '3 ft. 3 in.',
  'Nidoking': '4 ft. 7 in.',
  'Scyther': '4 ft. 11 in.',
  'Zubat': '2 ft. 7 in.',
  'Charmander': '2 ft. 0 in.',
  'Electrode': '3 ft. 11 in.',
  'Moltres': '6 ft. 7 in.',
  'Gloom': '2 ft. 7 in.',
  'Flareon': '2 ft. 11 in.',
  'Kabuto': '1 ft. 8 in.',
  'Electabuzz': '3 ft. 7 in.',
  'Venonat': '3 ft. 3 in.',
  'Charizard': '5 ft. 7 in.',
  'Pikachu': '1 ft. 4 in.',
  'Machop': '2 ft. 7 in.',
  'Caterpie': '1 ft. 0 in.',
  'Kakuna': '2 ft. 0 in.',
  'Horsea': '1 ft. 4 in.',
  'Seaking': '4 ft. 3 in.',
  'Dewgong': '5 ft. 7 in.',
  'Hitmonchan': '4 ft. 7 in.',
  'Clefable': '4 ft. 3 in.',
  'Nidoran F': '1 ft. 4 in.',
  'Starmie': '3 ft. 7 in.',
  'Rhyhorn': '3 ft. 3 in.',
  'Nidoran M': '1 ft. 8 in.',
  'Ninetales': '3 ft. 7 in.',
  'Cubone': '1 ft. 4 in.',
  'Weedle': '1 ft. 0 in.',
  'Vileplume': '3 ft. 11 in.',
  'Clefairy': '2 ft. 0 in.',
  'Grimer': '2 ft. 11 in.',
  'Magneton': '3 ft. 3 in.',
  'Mr. Mime': '4 ft. 3 in.',
  'Lapras': '8 ft. 2 in.',
  'Staryu': '2 ft. 7 in.'
}
